version: '3.8'
services:
  frontend:
    image: product-webapp
    container_name: prodwebapp
    build:
      context: .
    ports:
      - "82:80"
    networks:
      - app_net

networks:
  app_net:
    external: true
