---
- hosts: all
  become_user: root
  vars:
   master: /home/nixhal/hhh.lyric
   workers: /devops
   perm: 770

  tasks:
  - name: Copy files to worker nodes
    copy: 
      src: "{{ master }}"
      dest: "{{ workers }}"
      owner: nixhal
      group: narendra
      mode: "{{ perm }}"
    tags:
    - vaar

  - name: Archive files
    archive:
      path: "{{ workers }}"
      dest: "{{ workers }}/ansible.tar"

  - name: Unarchive files
    unarchive:
      src: "{{ workers }}/ansible.tar"
      dest: /home/nixhal
      remote_src: yes
    tags:
    - unarchive
