---
- hosts: all
  become: yes

  tasks:
  - name: Copy bulk lyrics using fileglob or say direct cp using *, copies all items related to lyrics_*
    copy:
      src: "{{ item }}"
      dest: /devops/
      owner: root
      group: root
      mode: '0750'
    with_fileglob:
    - "/home/nixhal/lyrics_*"
