---
- name: Creating a symlink to those site1 & site2 into sites-enabled
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "/etc/nginx/sites-available/site1", dest: "/etc/nginx/sites-enabled/site1" }
  notify:
  - Restart nginx
