---
- hosts: servers
  become_user: root
  
  tasks:
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
    loop: 
    - openjdk-17-jdk
    - tree
    - git 
    - curl
 
