---
- hosts: all
  become: yes

  tasks:
  - name: Copy files using loops
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    loop:
    - { src: "/home/nixhal/cmpunk_cop.lyric", dest: "/home/", owner: "root", group: "root", mode: "755" }
    - { src: "/home/nixhal/viper.lyric", dest: "/home/nixhal", owner: "root", group: "nixhal", mode: "775" } 
    - { src: "/home/nixhal/warpigs.lyric", dest: "/home/", owner: "nixhal", group: "root", mode: "700" } 
    - { src: "/home/nixhal/despasito.lyric", dest: "/home/", owner: "root", group: "root", mode: "555" } 

