---
- hosts: all
  ignore_errors: true
  
  tasks:
  - name: Create user
    user:
      name: Agent
      state: present
      owners: nixhal
      groups: groups

  - name: Copy files
    copy:
      src: "{{ item }}"
      dest: /home/nixhal
    with_fileglob:
    - "/home/nixhal/money*"

