---
- hosts: all
  become_user: root

  tasks:
  - name: Copy files to worker nodes
    copy: 
      src: /home/nixhal/songlyric
      dest: /home/nixhal
      owner: nixhal
      group: narendra
      mode: '770'

  - name: Archive files
    archive:
      path: /home/nixhal/songlyric
      dest: /home/nixhal/lyrics.tar

  - name: Unarchive files
    unarchive:
      src: /home/nixhal/lyrics.tar
      dest: /home
      remote_src: yes
    tags:
    - unarchive

  - name: Copying or Fetching from workernodes to masternode including the timestamp of file
    fetch:
      src: /home/nixhal/lyrics.tar
      dest: "/home/nixhal/lyrics_{{ ansible_date_time.date }}_{{ ansible_date_time.hour}}-{{ ansible_date_time.minute }}.tar"
      flat: yes
    tags:
    - fetch
 
  - name: Copy file to all groups
    copy:
      src: /home/nixhal/viper.lyric
      dest: /home/nixhal
      owner: nixhal
      group: narendra
      mode: '755'
    tags:
    - cp

  - name: Create a symlink
    file:
      src: /home/nixhal/viper.lyric
      dest: /devops/musiclyric/wwe/randyorton.lyric
      state: link
    tags:
    - link
