version: '3.8'

services:
  backend:
    image: product-service
    container_name: product-service-app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mydb:3306/product?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: nix
      SPRING_DATASOURCE_PASSWORD: nix123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update       
      SPRING_JPA_SHOW_SQL: true

#    volumes:
#      - ./application.properties:/app/config/application.properties
#    environment:
#      SPRING_CONFIG_LOCATION: 'file:/app/config/application.properties' 
    networks:
      - app_net

networks:
  app_net:
    external: true
