---
- hosts: all
  become: yes
  vars:
    package: nginx
    node1: workernode1
    node2: workernode2
    s1: site1
    s2: site2

  tasks:
  - name: Install nginx server on workernodes
    apt:
      name: "{{ package }}"
      state: present
    
  - name: Start & enable nginx service
    service:
      name: "{{ package }}"
      state: started
      enabled: true
  
  - name: Create project directory based on node
    file:
      path: "/var/www/{{ item.path }}"
      state: directory
    loop:
    - { node: "{{ node1 }}", path: "{{ s1 }}" }
    - { node: "{{ node2 }}", path: "{{ s2 }}" }
    when: ansible_nodename == item.node
 
  - name: Copying projects to their respective sites based on node
    synchronize:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      recursive: yes
    loop:
    - { src: "/home/nixhal/graphic_project/", dest: "/var/www/site1", node: "{{ node1 }}" }
    - { src: "/home/nixhal/health_project/", dest: "/var/www/site2", node: "{{ node2 }}" }
    when: ansible_nodename == item.node 

  - name: Moving the files site1 & site2 into /etc/nginx/sites-available directory inside the workernodes
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
    - { src: "/home/nixhal/graphic_project/{{ s1 }}", dest: "/etc/nginx/sites-available", node: "{{ node1 }}" }
    - { src: "/home/nixhal/health_project/{{ s2 }}", dest: "/etc/nginx/sites-available", node: "{{ node2 }}" }
    when: ansible_nodename == item.node
    notify:
    - Restart Nginx

  - name: Creating a symlink to those site1 & site2 into sites-enabled
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
    - { src: "/var/www/site1/{{ s1 }}", dest: "/etc/nginx/sites-enabled/site1", node: "{{ node1 }}" }
    - { src: "/var/www/site2/{{ s2 }}", dest: "/etc/nginx/sites-enabled/site2", node: "{{ node2 }}" }
    when: ansible_nodename == item.node
    notify:
    - Restart Nginx
  
  handlers:    
  - name: Restart Nginx
    service:
      name: "{{ package }}"
      state: restarted
  
  - name: Adding new contents into /etc/hosts file
    lineinfile:
      path: /etc/hosts
      line: "{{ item.line }}"
    loop:
    - { line: '192.168.1.11  www.site1.com', node: "{{ node1 }}" }
    - { line: '192.168.1.12  www.site2.com', node: "{{ node2 }}" }
    when: ansible_nodename == item.node
