--- 
- name: Copy all files
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    recursive: yes
  loop:
  - { src: "graphic_project/", dest: "/var/www/site1" }
  - { src: "site1", dest: "/etc/nginx/sites-available" }
  notify:
  - Restart nginx
