---
- import_tasks: install.yml
- import_tasks: service.yml
- import_tasks: directory.yml
- import_tasks: copy.yml
- import_tasks: link.yml



  #- include_tasks: install.yml
  #- include_tasks: install.yml
  #- include_tasks: install.yml
  #- include_tasks: install.yml
  #- include_tasks: install.yml
