---
- hosts: worker
  become_user: root

  tasks:
  - name: Create group
    group:
      name: sandarva
      state: absent

  - name: Create user
    user:
      name: bhattarai
      state: absent
