---
- hosts: servers
  become_user: root

  tasks:
  - name: Create groups using loop
    group:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - name: bam
      state: present
    - name: nagar
      state: present

  - name: Create users using loop
    user:
      name: "{{ item.name}}"
      state: "{{ item.state}}"
      groups: "{{ item.groups }}"
      append: yes
    loop:
    - name: bhuvan
      state: present
      groups: bam
    - name: Ajay
      state: present
      groups: nagar
