---
- hosts: servers
  become_user: root

  tasks:
  - name: Create user using loop
    user:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - name: samantha
      state: present
    - name: bibas
      state: present

  - name: Create group using loop
    group:
      name: "{{ item.name}}"
      state: "{{ item.state}}"
    loop:
    - name: Irwin
      state: present
    - name: Basnet
      state: present
